files:
  - source: /vi/*.json
    translation: /%locale%/%file_name%.json
    languages_mapping:
      locale:
        en: en
        vi: vi
        vi-x-tay: vi-x-tay
        id: id
        ms: ms
        th: th
        km: km
        lo: lo
        my: my
        tl: tl
        pt: pt
        zh-CN: zh-Hans
        zh-TW: zh-Hant